line-length = 110
target-version = "py312"
extend-exclude = ["*/migrations/*", ".venv", "staticfiles"]

[lint]
select = ["E", "F", "W", "I", "B", "UP", "DJ"]
ignore = ["E501", "B904", "DJ001", "DJ008"]
