# Generated by Django 5.2.17 on 2026-10-04 09:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "good_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=5,
                        verbose_name="Healthy up to (%)",
                    ),
                ),
                (
                    "warn_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("2.00"),
                        max_digits=5,
                        verbose_name="Watch up to (%)",
                    ),
                ),
                (
                    "cycle_days",
                    models.PositiveIntegerField(
                        default=90, verbose_name="Audit cycle (days)"
                    ),
                ),
                (
                    "soon_days",
                    models.PositiveIntegerField(
                        default=15, verbose_name="Due-soon window (days)"
                    ),
                ),
                (
                    "auditor_can_publish",
                    models.BooleanField(
                        default=False, verbose_name="Auditors can publish audits"
                    ),
                ),
                (
                    "session_timeout_minutes",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Session timeout (minutes)"
                    ),
                ),
                (
                    "signed_url_minutes",
                    models.PositiveIntegerField(
                        default=10, verbose_name="File link expiry (minutes)"
                    ),
                ),
                (
                    "notify_new_audit",
                    models.BooleanField(
                        default=True,
                        verbose_name="Email clients when an audit is published",
                    ),
                ),
                (
                    "notify_monthly_summary",
                    models.BooleanField(
                        default=True, verbose_name="Send the monthly summary on the 1st"
                    ),
                ),
                (
                    "notify_missing_files",
                    models.BooleanField(
                        default=True,
                        verbose_name="Send the daily missing-files reminder",
                    ),
                ),
                ("last_backup_at", models.DateTimeField(blank=True, null=True)),
                ("last_backup_note", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "app settings",
            },
        ),
    ]
