# Generated by Django 5.2.17 on 2026-10-04 09:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=160, verbose_name="Company name")),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("logo_key", models.CharField(blank=True, max_length=500)),
                (
                    "contact_emails",
                    models.TextField(
                        blank=True,
                        help_text="One or more, separated by commas.",
                        verbose_name="Contact emails",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "good_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Healthy up to (%)",
                    ),
                ),
                (
                    "warn_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Watch up to (%)",
                    ),
                ),
                (
                    "cycle_days",
                    models.PositiveIntegerField(
                        default=90, verbose_name="Audit cycle (days)"
                    ),
                ),
                (
                    "soon_days",
                    models.PositiveIntegerField(
                        default=15, verbose_name="Due-soon window (days)"
                    ),
                ),
                (
                    "notify_on_publish",
                    models.BooleanField(
                        default=True,
                        verbose_name="Email them when a new audit is published",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["sort_order", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("client", "name"), name="uniq_category_per_client"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=120)),
                ("city", models.CharField(blank=True, max_length=80)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stores",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("client", "code"), name="uniq_store_code_per_client"
                    )
                ],
            },
        ),
    ]
