# Generated by Django 5.2.17 on 2026-10-04 09:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferenceCounter",
            fields=[
                (
                    "year",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                ("last", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Audit",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("audit_date", models.DateField()),
                (
                    "audit_type",
                    models.CharField(
                        choices=[
                            ("physical", "Physical stock audit"),
                            ("surprise", "Surprise audit"),
                            ("cycle", "Cycle count"),
                            ("closing", "Closing audit"),
                        ],
                        default="physical",
                        max_length=20,
                    ),
                ),
                (
                    "shift",
                    models.CharField(
                        choices=[
                            ("morning", "Morning"),
                            ("afternoon", "Afternoon"),
                            ("night", "Night"),
                        ],
                        default="morning",
                        max_length=20,
                    ),
                ),
                (
                    "series",
                    models.CharField(
                        choices=[("full", "Full audit"), ("other", "Other audit")],
                        default="full",
                        editable=False,
                        max_length=10,
                    ),
                ),
                (
                    "sale_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Note from Audix")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("deleted", "Deleted"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("reference", models.CharField(max_length=20, unique=True)),
                (
                    "stock_qty",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "stock_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "physical_qty",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "physical_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "damage_qty",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "damage_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "wbc_qty",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "wbc_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "total_qty",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "total_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "diff_qty",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "diff_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "var_pct_stock",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "var_pct_sale",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                ("status_label", models.CharField(blank=True, max_length=12)),
                ("remark", models.TextField(blank=True)),
                (
                    "largest_shortage_category",
                    models.CharField(blank=True, max_length=80),
                ),
                ("aging_days", models.IntegerField(blank=True, null=True)),
                ("delay_days", models.IntegerField(blank=True, null=True)),
                ("is_imported", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audits",
                        to="clients.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "previous_audit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="audits.audit",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audits",
                        to="clients.store",
                    ),
                ),
            ],
            options={
                "ordering": ["-audit_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditFile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("audit_excel", "Audit Excel"),
                            ("variance_report", "Variance report"),
                            ("scanned_data", "Scanned data"),
                            ("signoff", "Signoff copy"),
                            ("photo", "Evidence photograph"),
                        ],
                        max_length=20,
                    ),
                ),
                ("storage_key", models.CharField(max_length=500)),
                ("original_name", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=120)),
                ("size_bytes", models.BigIntegerField(default=0)),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("thumbnail_key", models.CharField(blank=True, max_length=500)),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="audits.audit",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["kind", "sort_order", "uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stock_qty",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "stock_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "physical_qty",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "physical_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "damage_qty",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "damage_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "wbc_qty",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "wbc_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "total_physical_qty",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "total_physical_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "diff_qty",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "diff_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="audits.audit",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="clients.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Observation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("shortage", "Shortage"),
                            ("damage", "Damage"),
                            ("wbc", "WBC"),
                            ("process_gap", "Process gap"),
                            ("good_practice", "Good practice"),
                        ],
                        default="shortage",
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("text", models.TextField(blank=True)),
                ("recommendation", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="audits.audit",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="clients.category",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="FollowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("done", "Done"),
                            ("in_progress", "In progress"),
                            ("not_done", "Not done"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followups",
                        to="audits.audit",
                    ),
                ),
                (
                    "previous_observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followups",
                        to="audits.observation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ObservationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("shortage", "Shortage"),
                            ("damage", "Damage"),
                            ("wbc", "WBC"),
                            ("process_gap", "Process gap"),
                            ("good_practice", "Good practice"),
                        ],
                        max_length=20,
                    ),
                ),
                ("slot", models.PositiveSmallIntegerField(default=1)),
                (
                    "text",
                    models.TextField(
                        help_text="Shortage: the cause sentence. Damage/WBC: may use {pct}, {category}, {units}."
                    ),
                ),
                ("recommendation", models.TextField()),
            ],
            options={
                "ordering": ["kind", "slot"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "slot"), name="uniq_template_slot"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="audit",
            index=models.Index(
                fields=["client", "store", "audit_date"], name="audit_client_store_date"
            ),
        ),
        migrations.AddIndex(
            model_name="audit",
            index=models.Index(
                fields=["client", "audit_date"], name="audit_client_date"
            ),
        ),
        migrations.AddIndex(
            model_name="audit",
            index=models.Index(fields=["client", "status"], name="audit_client_status"),
        ),
        migrations.AddIndex(
            model_name="auditfile",
            index=models.Index(fields=["audit", "kind"], name="auditfile_audit_kind"),
        ),
        migrations.AddConstraint(
            model_name="auditline",
            constraint=models.UniqueConstraint(
                fields=("audit", "category"), name="uniq_line_per_category"
            ),
        ),
        migrations.AddConstraint(
            model_name="followup",
            constraint=models.UniqueConstraint(
                fields=("audit", "previous_observation"), name="uniq_followup"
            ),
        ),
    ]
